title: <p align="center"> Pankaj Chauhan </p>
logo: /assets/img/PankajChauhan.jpg
description:
  <p align="center">
  <a href="https://www.linkedin.com/in/pankajchauhan1212/">LinkedIn</a> |
  <a href="https://github.com/pankajchauhan1212">GitHub</a>

theme: jekyll-theme-minimal
